name: Python package

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:latest
        env:
          POSTGRES_USER: user1
          POSTGRES_PASSWORD: pwd1
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
#        python: [3.5, 3.6, 3.7, 3.8]
        python: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Installing Geospatial libraries
        run: sudo apt-get install binutils libproj-dev gdal-bin
      - name: Install dependencies
        run: |
          pip install tox tox-gh-actions psycopg2
      - name: Run tests
        run: tox -e py38-django111-postgresql -v
